export const STORAGE_KEY_ORDER = "APART_TRADE_LIST_APP:ORDER";
export const STORAGE_KEY_FAVORITE_LIST = "APART_TRADE_LIST_APP:FAVORITE_LIST";
export const STORAGE_KEY_SAVED_APART_LIST =
  "APART_TRADE_LIST_APP:STORAGE_KEY_SAVED_APART_LIST";
