export const TRADE_LIST_ORDER_STORAGE_KEY = "APART_TRADE_LIST_APP:TRADE_LIST_ORDER";
export const FAVORITE_LIST_STORAGE_KEY = "APART_TRADE_LIST_APP:FAVORITE_LIST";
export const APART_LIST_STORAGE_KEY = "APART_TRADE_LIST_APP:APART_LIST";
